### ISSUE TITLE
Stocking Certain Items 

### ISSUE THREAD

**Issue by Solidaritx** [Chuckleberry-Finn/pz-shops#12]
I am unable to add the vanilla Walkie Talkies into the store stock (admin). 
Would mod load order be messing with this? 
<img width="813" alt="Screenshot 2023-08-05 031825" src="https://github.com/Chuckleberry-Finn/pz-shops/assets/141477088/233ec5b0-b01e-41b4-a8eb-d416db38029b">

**Comment by Solidaritx** [comment]
We were able to uploaded them before, but not sure why we cant anymore. 
<img width="300" alt="image" src="https://github.com/Chuckleberry-Finn/pz-shops/assets/141477088/bdb4cae6-c26d-4e41-8627-4f6aca622f18">

**Comment by Solidaritx** [comment]
Places at the front of the load order, dropped 2 errors, still cant add radios
<img width="795" alt="image" src="https://github.com/Chuckleberry-Finn/pz-shops/assets/141477088/6ff3fd79-a5a5-4731-b603-aceb542b9a72">

**Comment by Solidaritx** [comment]
SOLVED: Im a newb, my buddy just seared the item id, instead of search bar, and it worked

**Comment by Ender2point0** [comment]
I came here for the same issue, but I can't understand how you fixed it

**Comment by Chuckleberry-Finn** [comment]
The issue is related to special characters like `-` breaking the regex (I assume). The work around is to change the input mode to `type` instead of `name`.

**Comment by Chuckleberry-Finn** [comment]
The other errors are all related to faction banking - which is a sub mod. I may just envelope that mod into the main mod - not sure why it's breaking as the bugs suggest. Make sure you've resubscribed to that mod to ensure you're on the latest version.

**Comment by Solidaritx** [comment]
Switch category from Name to Type

Look up and use the item ID, (ex: Base.crips). I just spawn the item and
hit “edit” to look up the Id.

**Comment by Chuckleberry-Finn** [comment]
You can also drag and drop the item into the shop to generate it's type.

**Comment by Ender2point0** [comment]
The methods both of you have described some only works with some items and even then sometimes this happens. I've tried putting in an item with no special symbols but it still didn't work
![image](https://github.com/Chuckleberry-Finn/pz-shops/assets/71964554/825ed4a0-9cd2-42d9-8696-844d5a4add82)

**Comment by Chuckleberry-Finn** [comment]
The store not being accessible means it is in manage mode.

**Comment by Chuckleberry-Finn** [comment]
See: #17
