### ISSUE TITLE
Incompatible problem with "Inventory Tetris mod" 

### ISSUE THREAD

**Issue by AlexNTFox** [Chuckleberry-Finn/pz-shops#14]
With new inventory system from this mod https://steamcommunity.com/sharedfiles/filedetails/?id=2982070344 large sizes items, like Assault Rifles cannot by sold to shops, because shop require holding item in primary character inventory. But i still can buy large size items, and sold small sizes items. So, why not making enableable option, like "sold items from backpacks and other containers" or something like else?

Here some pics

![Project Zomboid Screenshot 2023 08 17 - 00 21 54 71](https://github.com/Chuckleberry-Finn/pz-shops/assets/12477741/ff594226-138e-4caa-a8ff-3c1e09bc7b33)
![Project Zomboid Screenshot 2023 08 17 - 00 21 58 36](https://github.com/Chuckleberry-Finn/pz-shops/assets/12477741/e5413f47-0824-45aa-8129-edf63ca38d0c)

**Comment by Chuckleberry-Finn** [comment]
Fixed
