### ISSUE TITLE
VHS Tapes from Vanilla are all grouped together and can't be sold. 

### ISSUE THREAD

**Issue by jonathanjacobs** [Chuckleberry-Finn/pz-shops#23]
If you add a VHS tape it ends up defaulting to Base.VHS_Retail - which can't be bought/sold either. I discovered this trying to sell surplus Cooking and Survival skill tapes - it didn't work.

**Comment by jonathanjacobs** [comment]
any chance this can be fixed? would be great if we could buy/sell specific VHS tapes in game. I looked at the LUA and think it has to do with the way the "name" of VHS tapes are encoded versus how it's done with books, etc.

**Comment by Chuckleberry-Finn** [comment]
Making shops handle same type but different named item is on the to-do.

**Comment by jonathanjacobs** [comment]
Does this work now?
