### ISSUE TITLE
Items with No Category can't be bought or sold

### ISSUE THREAD

**Issue by jonathanjacobs** [Chuckleberry-Finn/pz-shops#25]
Our server uses a variety of mods that create new items. Many of these can be bought/sold in the stores without issue - but one thing we have noticed is that items where there is no Category set can't be sold. They can be added to the list of "Sellable" items after going into the Manage Store menu, but when you set prices or minimum store quantities, the values don't save after clicking the [+] button. I think this is a bug, ye?

**Comment by Chuckleberry-Finn** [comment]
What kinds of items don't have a category? I'm not sure that should cause a problem - but under normal circumstances all items should have categories.

**Comment by jonathanjacobs** [comment]
I actually found a work around - I'll post some screen shots here so you can see what I'm talking about.

**Comment by Chuckleberry-Finn** [comment]
This is a known issue - the regex does not like special characters. Setting that option to type or category will get around the issues with names.

**Comment by Chuckleberry-Finn** [comment]
See: #17
