### ISSUE TITLE
Infinite Money Bug

### ISSUE THREAD

**Issue by jonathanjacobs** [Chuckleberry-Finn/pz-shops#26]
This seems to only affect some items, but it was reported to me by one of our server players (they don't have a github account, which is why I'm reportign it). I confirmed the bug as well and have a short video showing it happening. 

how to reproduce
1. equip a Trauma Bag (the red duffle bags) in your seconary hand
2. Put a suture needle or a suture needle holder in the bag
3. drag the item from the bag to the store that will buy those items
4. Click trade. 
5. The item does not get removed from the bag, but the store pays out the money for the trade in value of the item. The store's inventory does not change either (so no item is traded, but the money is recieved by the player).

I've attached a video showing this happening.
https://github.com/Chuckleberry-Finn/pz-shops/assets/64888/0567fc83-495c-4ea5-bf4a-698c886e27d6

**Comment by Chuckleberry-Finn** [comment]
Thank you, it's probably able to identify the item is in the player's inventory recursively but not able to remove it for some reason.

**Comment by jonathanjacobs** [comment]
Fortunately I have a relatively small server- so the abuse isn’t going to be too much of an issue. But it is a way for someone to basically get infinite money. So far seems to work with any “first aid” item
