### ISSUE TITLE
Money placed on the ground can be dragged into wallet to deposit multiple times and will remain on inventory tab until player moves.

### ISSUE THREAD

**Issue by aandrew132** [Chuckleberry-Finn/pz-shops#27]
when currency is withdrawn and placed on the ground, if it is dragged into the wallet manually, the item will still register on the ground and can be deposited multiple times until the character moves and inventory list updates, see attached video.

https://github.com/Chuckleberry-Finn/pz-shops/assets/1308812/f7fe4def-d819-4808-8cf2-9d1b050a57de

**Comment by Chuckleberry-Finn** [comment]
Fixes with #34 .
