### ISSUE TITLE
Singleplayer not working 

### ISSUE THREAD

**Issue by Asharzman** [Chuckleberry-Finn/pz-shops#32]
So here's the run down:
- Set up the shop
- Put items in there/set it up like you would
- Save & Quit
- Load save
- Shop is now unavailable and all setup is gone

I tested this with other mods present and with only the Shops and Traders enabled, and on both cases the issue persists, where the shop is gone

**Comment by Chuckleberry-Finn** [comment]
Should be fixed next update. a63f4674e6aa375952152045ff4f2700c833e6d7
