### ISSUE TITLE
You can destroy the store with the Sledgehammer and keep everything inside.

### ISSUE THREAD

**Issue by xxxRetroxxx** [Chuckleberry-Finn/pz-shops#33]
From what I have tested you can't dismantle the store if you are not an administrator but you can destroy it with the Sledgehammer and keep everything inside.

**Comment by Chuckleberry-Finn** [comment]
I will have to retest this, as the destroy action should be the same function. Are you using other mods that might modify the sledgehammer's process?

**Comment by xxxRetroxxx** [comment]
I do not use any mod that modifies the sledgehammer. I also used another store mod called simply Shops with the same configuration and those I could not destroy in any way.

**Comment by Chuckleberry-Finn** [comment]
I cannot break stores with a sledgehammer in my tests. Can you describe your actions exactly, even going as far as to explain what keys or menus you're using?

Any mods that modify the destroy action can also be overwriting the code poorly.

**Comment by Chuckleberry-Finn** [comment]
I tried a MP run with a number of mods installed ,and scrap warrior/weapons seems to overwrite the destroy action. I'm not sure if you use that mod or not.

**Comment by xxxRetroxxx** [comment]
Just, we use Scrap Armor, Scrap Guns and Scrap Weapons. I'll try to remove them and see if it solves the problem. Thank you very much

**Comment by Chuckleberry-Finn** [comment]
You can load them first before this mod, and it should alleviate the issue.
