### ISSUE TITLE
Infinite money in duplicate

### ISSUE THREAD

**Issue by xxxRetroxxx** [Chuckleberry-Finn/pz-shops#34]
If you put the money on the ground and drag it directly to the character tab to the part that says wallet, the money goes into your wallet but stays on the ground, which allows you to do it again infinitely until the character moves.

**Comment by Chuckleberry-Finn** [comment]
Confirmed there is an issue/error that is cutting off the clearance process.

**Comment by xxxRetroxxx** [comment]
Could this be fixed in future updates?

**Comment by Chuckleberry-Finn** [comment]
Fixed: c214cd726664c16895357b9a998f516aab94389e
