### ISSUE TITLE
Suggestion And Some Bug

### ISSUE THREAD

**Issue by PgRusher** [Chuckleberry-Finn/pz-shops#39]
Hi 
can I ask for a feature please, I want to do something that does not lose money when the player dies? a permanent wallet for each player on the server is it possible? 
and about the bug, it has a bug sometimes when you try to drag and drop the money back into your wallet it does not work. you know when someone places money into their wallet so it is safe for him after he dies or sets an option for sandbox letting the admin decide about it the money is lost forever or stands permanent for the player.

**Comment by Chuckleberry-Finn** [comment]
The drag to wallet bug will be fixed in an upcoming patch. I can look into the wallet thing.

**Comment by PgRusher** [comment]
Hi 
thanks i asking that because im runnig a server so thats really important for me that permenant wallet things im really happy to hear that you are working on it if u need any help i can help you in this project i have a little knowledge dm me in discord:fetrush
