### ISSUE TITLE
[Q] Importing stores from other saves

### ISSUE THREAD

**Issue by mattszymanko** [Chuckleberry-Finn/pz-shops#40]
Hello,

This isn't really an issue so much as it is more of a question - that is, how exactly would one import store data from an already existing save to a new one?

Cheers!

**Comment by Chuckleberry-Finn** [comment]
When you go into assign shops there's an import/export option which writes to a text file. This is not where the shops are saved to - simply a means to edit the potentially large file.

**Comment by mattszymanko** [comment]
Great, thank you. Have a good one.
