### ISSUE TITLE
Players unable to access store randomly, some items are also cannot be sold

### ISSUE THREAD

**Issue by blackbaron890** [Chuckleberry-Finn/pz-shops#44]
[Uploading console.txt…]()

**Comment by blackbaron890** [comment]
[console.txt](https://github.com/Chuckleberry-Finn/pz-shops/files/13930314/console.txt)

**Comment by jonathanjacobs** [comment]
I have a similar issue, and leaving/returning or waiting doesn't seem to fix it. For example - on our server we have "Spiffo Stores" that buy&sell all things "Spiffo" - but a few items can't be sold (the store will buy them though). For example "Spiffo Backpacks". 
![image](https://github.com/Chuckleberry-Finn/pz-shops/assets/64888/6139f09f-6c39-4ff5-8408-98fee43e538e)
Notably, when managing this store the item gets a [!] in front of the name, and then when returning the store to active mode (leaving the manage mode), the item is not listed at all despite there being multiple items in the inventory.

**Comment by Chuckleberry-Finn** [comment]
I believe the [ ! ] warning is due to there not being a texture set, but curiously it does display fine - at least for the Spiffos. What mod adds these?
