### ISSUE TITLE
bug: Unable to list items with Moveable type in shop UI

### ISSUE THREAD

**Issue by aoqia194** [Chuckleberry-Finn/pz-shops#52]
With this mod, trying to list items in the shop UI with the Moveable type will warrant an Invalid Item message when the item is dragged into the interface.

I am reporting this issue on the behalf of a server owner, so I do not have any sufficient example evidence as of current. If you glance at the code, and it is not apparent, I can try and gather some evidence after the fact.

**Comment by Chuckleberry-Finn** [comment]
This is a known issue, and currently being worked on. Thank you for the reminder to get back to it. 👍

**Comment by aoqia194** [comment]
Thank you!
