### ISSUE TITLE
FS Expansion

### ISSUE THREAD

**Issue by Chuckleberry-Finn** [Chuckleberry-Finn/pz-shops#6]
- [ ] Able to check item condition being sold. Could be in parentheses behind the name i.e. Bat (25/25)
- [x] No collateral needed in the shop, meaning we can set any tile as the shop similar to shops/traders. 
- [ ] Buy/Sell orders with specific quantities of items up to infinity. 
- [ ] All items have temporary limits that regenerate over time to prevent one person from buying all the items.
- [ ] Sell order type that a player can only buy one of until the admin resets it. (used for entry tickets to events)

- [ ] Shop owner and managers that can be assigned. 
- [x] Shop inventory only shows up to Owner/Manager. 
- [ ] Full offline barter system, instead of a "currency" players can just choose what item they want to buy/sell that is in the shops inventory and then choose what they're willing to trade for it, which of course could include the currency or any denomination of it, or any single item **type** but any number of that item type. This solves any server who wants to run a custom currency, but does force the use of a physical currency.
     example: Trading 1 Box of Shotgun ammo for 1 box of .223 Ammo (Inventory 25)
     Inventory would list how many the shop _could_ buy/sell
- [ ] If you want to put in something for an account based currency or "stored" currency you're welcome to, we can discuss this further if you think it's necessary.

- [x] Create a credit system per shop
- [ ] Full logging of both admin and player shops in lua files, preferred by shop owner's name and shop x,y,z.
- [ ] Shops are automatically powered so that fridges and freezers work but don't provide power to items near them (for fridges)
- [ ] Shops expire after the owner has failed to login after x amount of time.
- [ ] Allow the purchase of x number of items via the UI.

**Comment by ChuckTheSheep** [comment]
Close #4

**Comment by ChuckTheSheep** [comment]
Close #5
